/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // E-Greetings Design System Colors
        "surface": "#fff8f2",
        "surface-dim": "#e1d9ce",
        "surface-bright": "#fff8f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fbf2e7",
        "surface-container": "#f5ede2",
        "surface-container-high": "#f0e7dc",
        "surface-container-highest": "#eae1d7",
        "on-surface": "#1f1b15",
        "on-surface-variant": "#4e4637",
        "inverse-surface": "#343029",
        "inverse-on-surface": "#f8efe5",
        "outline": "#807665",
        "outline-variant": "#d1c5b2",
        "surface-tint": "#795900",
        "primary": "#6f5100",
        "on-primary": "#ffffff",
        "primary-container": "#8b6914",
        "on-primary-container": "#fff0da",
        "inverse-primary": "#ecc165",
        "secondary": "#615e59",
        "on-secondary": "#ffffff",
        "secondary-container": "#e8e2db",
        "on-secondary-container": "#67645e",
        "tertiary": "#34568c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4e6fa6",
        "on-tertiary-container": "#eff2ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdfa0",
        "primary-fixed-dim": "#ecc165",
        "on-primary-fixed": "#261a00",
        "on-primary-fixed-variant": "#5c4300",
        "secondary-fixed": "#e8e2db",
        "secondary-fixed-dim": "#cbc6bf",
        "on-secondary-fixed": "#1d1b17",
        "on-secondary-fixed-variant": "#494641",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#aac7ff",
        "on-tertiary-fixed": "#001b3e",
        "on-tertiary-fixed-variant": "#23477b",
        "background": "#fff8f2",
        "on-background": "#1f1b15",
        "surface-variant": "#eae1d7",
        "surface-glass": "rgba(255, 252, 245, 0.85)",
        "surface-border": "rgba(139, 105, 20, 0.2)",
        "text-muted": "#6B6560",
        "accent-gold": "#8B6914",
        "white": "#FFFFFF",
      },
      fontFamily: {
        "headline": ["'Noto Serif'", "serif"],
        "body": ["'Manrope'", "sans-serif"],
        "label": ["'Manrope'", "sans-serif"],
        "brand-logo": ["'Noto Serif'", "serif"],
        "nav-link": ["'Inter'", "sans-serif"],
        "nav-link-active": ["'Inter'", "sans-serif"],
        "label-sm": ["'Inter'", "sans-serif"],
        "button-text": ["'Inter'", "sans-serif"],
      },
      fontSize: {
        "brand-logo": ["22px", { lineHeight: "1.2", fontWeight: "600" }],
        "nav-link": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "nav-link-active": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "button-text": ["14px", { lineHeight: "1", fontWeight: "600" }],
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      keyframes: {
        "scale-in": {
          "from": { opacity: "0", transform: "scale(0.92)" },
          "to":   { opacity: "1", transform: "scale(1)" },
        },
        "fade-up": {
          "from": { opacity: "0", transform: "translateY(16px)" },
          "to":   { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "from": { opacity: "0" },
          "to":   { opacity: "1" },
        },
      },
      animation: {
        "scale-in":         "scale-in 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        "fade-up":          "fade-up 0.5s cubic-bezier(0.22, 1, 0.36, 1) both",
        "fade-in":          "fade-in 0.25s ease both",
        "scale-in-spring":  "scale-in 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) both",
      },
    },
  },
  plugins: [],
};
