version: '3.8'

services:
  gateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  identity-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  greeting-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  subscription-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  user-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  notification-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  admin-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  feedback-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
