<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\EGreetings.Greeting.Application\EGreetings.Greeting.Application.csproj" />
    <ProjectReference Include="..\EGreetings.Greeting.Infrastructure\EGreetings.Greeting.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared\EGreetings.Shared.Infrastructure\EGreetings.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
